chore(typing): Add `pyright` and fix errors (#1095)
## Description
Main goal is to avoid red squiggles if a contributor opens a `.py` file
in the workspace [^1].

**Where were the issues?**
See (a09f82b8e210afd1ef614a67f84395fd74e25c2f)

**How do we fix them?**
*I'm working on it*

[^1]: While using VSCode and
[Pylance](https://github.com/microsoft/pylance-release)

## Possible `__all__` follow-up
I can fix this here, *but* the diff will be 98% related to it.
Did mention before
(https://github.com/uwdata/mosaic/pull/1068#discussion_r3543675753) that
fixing it is important:

<details><summary>Show
<code>[reportUnsupportedDunderAll]</code></summary>
<p>

```py
mosaic/packages/vgplot/vgplot-python/vgplot/_generated/__init__.py:10:1
warning: Operation on "__all__" is not supported, so exported symbol list may be incorrect (reportUnsupportedDunderAll)
0 errors, 1 warning, 0 informations
```

</p>
</details>

There are many forms which are specified in [Typing spec - Library
interface (public and private
symbols)](https://typing.python.org/en/latest/spec/distributing.html#library-interface-public-and-private-symbols).
Which forms are supported by each type checker[^2] **vary** and so a
major issue in downstream projects is incomplete/invalid export
definitions.

[^2]: aaaaaaand now there are [7 type
checkers](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html)
🫠



### Example

This code will fail at runtime:
```py
def check_exports_bad() -> None:
    import vgplot

    _not_really_there = vgplot.attributes.align

check_exports_bad()
```
```py
AttributeError: module 'vgplot' has no attribute 'attributes'
```

#### Pyright
Because it doesn't understand the `__all__` definition *fully*, it is
inferring that `_generated.attributes.py` is available at the top level.
So it thinks that was valid and here you can see "Go to definition":

<img width="1085" height="390" alt="image"
src="https://github.com/user-attachments/assets/b515055f-86cc-4799-ae35-aa0d53b2aa9e"
/>


#### ty
However, with `ty` this is correctly reported as an error:

```rust
error[unresolved-attribute]: Module `vgplot` has no member `attributes`
   --> packages/vgplot/vgplot-python/tests/test_python_api.py:480:25
    |
480 |     _not_really_there = vgplot.attributes.align
    |                         ^^^^^^^^^^^^^^^^^
    |

Found 1 diagnostic
```

#### Others
- (https://github.com/facebook/pyrefly) matches `ty`
- (https://github.com/python/mypy) doesn't recognise anything in
`__all__`
- It reports `attributes` as an error, but also **316 others** that are
in the runtime definition

## Related
- #1088
- https://github.com/microsoft/pyright
- https://github.com/vega/altair/pull/3482