feat: makeClient API (#677)
* feat: makeClient API

Add a `makeClient` API to make it easier to build Mosaic views with modern frameworks such as React or Svelte.

Here is how one might use it in Svelte 5 syntax. This examples shows a simple sum of a given field.

```svelte
<script>
let { table, field, filter, coordinator } = $props();

let currentSum = $state(null);

$effect(() => {
    // Create the Mosaic client, and re-create it whenever any of the table, field,
    // filter, coordinator props change. Note that for the filter, a "change" here means
    // the filter is set to a new instance of Selection, rather than a change of the
    // current selection's value.
    let client = makeClient({
        coordinator: coordinator,
        selection: filter,
        prepare: async () => {
            // Obtain any information needed before running queries.
            let infos = await coordinator.query(...); // query directly.
            let fieldInfos = await coordinator.queryFieldInfos(...); // or use the field info API for commonly used information.
            // Now you can set Svelte state or variables that the query method use.
        },
        query: (predicate) => {
            return Query.from(table)
                .select({ "sum": sql`SUM(${column(field)})` })
                .where(predicate);
        },
        queryResult: (data) => {
            currentSum = data[0].sum;
        },
        queryError: (error) => {
            console.error("query error", error);
        }
    });

    // Once the client is created, you may call the following on it:
    // client.requestUpdate(); // Tell the client to run a new query. This is throttled.
    // client.initialize(); // Re-initialize the client (prepare will be called again, and then an update is requested).

    return () => {
        // Destroy the previous client before the effect updates.
        client.destroy();
    }
});
</script>

<p>Sum of {field} is: {currentSum}</p>
```

# Conflicts:
#	package-lock.json

* style: clean up type imports

* docs: add links to frameworks and headings

* style: update comments and fix type for `query`

* chore: undo adding queryFieldInfo to coordinator

* chore: minimize lockfile changes

* fix tests

* test: test make-client

* docs: integrate docs and use const

* style: use const

* docs: update binding of table

* rename DynamicQueryClient to ProxyClient

* update comment for prepare

* Move docs

* fix doc links and react example code

---------

Co-authored-by: Donghao Ren <donghao@apple.com>